let _={};
const pegjs = require ('pegjs');
const fs = require ('fs');
_=fs.readFileSync ('./src/grammar.peg' , 'utf8');
_=pegjs.generate (_ , {output:'source'});
fs.writeFileSync ('./lib/index.js' , _);
const compile = reqiure ('../lib/index.js');
const CompFile = (name)=>{let _={};_=fs.readFileSync ('./src/' + name + '.ks' , 'utf8');
_=compile(_);
fs.writeFileSync ('./lib/' + name + '.js' , _);};
CompFile ('build');
